name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem or Use Case
      description: What problem does this solve? What's your use case?
      placeholder: I want to be able to...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions you've considered?

  - type: dropdown
    id: nist-control
    attributes:
      label: Related NIST Control
      description: Which security control does this relate to?
      options:
        - Not sure
        - AC (Access Control)
        - AU (Audit and Accountability)
        - CM (Configuration Management)
        - IA (Identification and Authentication)
        - MP (Media Protection)
        - RA (Risk Assessment)
        - SA (System and Services Acquisition)
        - SC (System and Communications Protection)
        - SI (System and Information Integrity)
        - Other

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
